# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name=b'name')),
                ('twitter', models.CharField(blank=True, max_length=15, verbose_name=b'twitter handle')),
                ('followers', models.IntegerField(default=0)),
                ('twitter_oauth_token', models.CharField(blank=True, max_length=50)),
                ('twitter_oauth_token_secret', models.CharField(blank=True, max_length=45)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('us_status', models.CharField(choices=[(b'C', b'US Citizen'), (b'R', b'US Resident (non-citizen)'), (b'O', b'Other')], max_length=1)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
